### PR TITLE
Update Popup Style Attributes: Place

### PR DESCRIPTION
**Pull request by shubham-kaushal**

### CODE REVIEW

**Comment by tenphi** [comment]
I don't see any reason we make the popup to behave visually like the popuplistbox. In most cases, a popup should be centered.

**Comment by shubham-kaushal** [comment]
To have consistency in the default styling, it's important.

The current styling looks a little odd.
image

**Comment by shubham-kaushal** [comment]
image
Looks Better

**Comment by shubham-kaushal** [comment]
Or we need to have a custom bottom radius only, no top radius.

**Comment by tenphi** [comment]
I got the idea. I will make some changes in another branch.

**Pull request closed without merging**
